### ISSUE TITLE
Classes and functions without valid component prefix

### ISSUE THREAD

**Issue by mudrd8mz** [Unplag/moodle-plagiarism_unplag#1]
See https://docs.moodle.org/dev/Plugin_contribution_checklist#Namespace-collisions for details. Functions like `unplag_get_score()` should be named like `plagiarism_unplag_get_score()`.

**Comment by mudrd8mz** [comment]
Additionally, classes like `UnApi` should either be namespaced, or with a valid prefix, too. Please see https://docs.moodle.org/dev/Coding_style#Namespaces

**Comment by Unplag** [comment]
Now API SDK and functions are namespaced.
