### ISSUE TITLE
Suspicious access to config_plugins tables

### ISSUE THREAD

**Issue by mudrd8mz** [Unplag/moodle-plagiarism_unplag#2]
Is there any special reason why the settings.php uses low level DB access to the `config_plugins` table, followed by the cache invalidation - instead of simply using the Moodle core API functions `get_config()` and `set_config()` for this?

**Comment by danmarsden** [comment]
probably copy/pasted from the urkund code - a better example would be the newer moorsp plugin. I keep meaning to tidy that up in the urkund code at some point.

**Comment by Unplag** [comment]
looked at moorsp and made the same

**Comment by danmarsden** [comment]
The old code pre-gsoc might have but the current code uses set_config correctly.
https://github.com/danmarsden/moodle-plagiarism_moorsp/blob/master/settings.php#L67

**Comment by mudrd8mz** [comment]
Is the cache invalidation still needed then?

**Comment by danmarsden** [comment]
no, it dates to some really old code that I wrote in the turnitin plugin which was copied to Urkund and never tidied up - there was a reason it was done that way back for the old turnitin code but it's not needed in the urkund (or turnitin one) anymore - you should be able to convert to using set_config here as well.
