### ISSUE TITLE
GPL v2 in the LICENSE file

### ISSUE THREAD

**Issue by mudrd8mz** [Unplag/moodle-plagiarism_unplag#3]
Note that inline PHP docs states that the license is "GNU GPL v3 or later", but the LICENSE file contains the GPL v2. Even though it is legally valid, it might be just clearer to have the GPL v3 text attached in the LICENSE file to avoid potential confusion.

**Comment by mudrd8mz** [comment]
For more details, see http://www.gnu.org/licenses/license-list.html#GPLv2

**Comment by Unplag** [comment]
attached GPL v3
