### ISSUE TITLE
Possible issues on sites with allow_url_fopen disabled

### ISSUE THREAD

**Issue by mudrd8mz** [Unplag/moodle-plagiarism_unplag#4]
As far as I understand it, if the site has `allow_url_fopen` disabled in their php.ini (e.g. for security reasons), your solution based on `stream_context_create()` in the unplagapi.class.php will not work. In the Moodle core itself, we make use of the `curl()` class for these purposes. Alternatively, this requirement might be explicitly mentioned at the plugin description page.

**Comment by stronk7** [comment]
Hi, just to add that, since long ago, we handle all downloads with the high level download_file_content() function. Internally it uses curl, supports proxies and all sort of stuff.

Hope it helps, ciao :-)

**Comment by Unplag** [comment]
Fixed.
