### ISSUE TITLE
Unclarified references to the plagiarism_urkund

### ISSUE THREAD

**Issue by mudrd8mz** [Unplag/moodle-plagiarism_unplag#5]
I can see some confusing references to the plagiarism_urkund plugin, at least in files ajax.js and track.php

Please note that sharing and re-using others' GPL'ed code is valid and encouraged. However, there are certain rules around it. See https://docs.moodle.org/dev/Plugin_contribution_checklist#Copyrights for some explanation.
- All your files should contain `@package plagiarism_unplag`
- The files not originally written by yourself must (according to the GPL statements) keep the original author's credits and copyrights, with your name added (e.g. as another `@copyright` line)
- Only files originally written by yourself can have yourself as the only `@copyright` holder

**Comment by migonium** [comment]
fixed

**Comment by Unplag** [comment]
fixed

**Comment by mudrd8mz** [comment]
track.php still reads `@package plagiarism_urkund`

**Comment by Unplag** [comment]
Fixed.
