### ISSUE TITLE
Custom curl implementation with suspicios options

### ISSUE THREAD

**Issue by mudrd8mz** [Unplag/moodle-plagiarism_unplag#7]
Your plugin description states "The data in your account is secure. Unplag encryption protects you from data leaks.". I don't understand why your classes/unplagapi.class.php then uses things like `curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, 0)` and `curl_setopt($curl, CURLOPT_SSL_VERIFYHOST, 0)`.

It is generally recommended to use the `curl` class wrapper provided by the Moodle core that better respects other settings, including the eventual proxy etc.

**Comment by Unplag** [comment]
fixed
