### ISSUE TITLE
Invalid parameters for set_config() and get_config()

### ISSUE THREAD

**Issue by mudrd8mz** [Unplag/moodle-plagiarism_unplag#9]
The settings.php seems to store its settings via `set_config()` call, providing `plagiarism` as the component name. That is weird. The third parameter to that function is supposed to be valid frankenstyle component name. Passing the plugin type name does not look right. Am I missing something?

**Comment by Unplag** [comment]
fixed.

**Comment by mudrd8mz** [comment]
Are you sure it really works? As far as I can see, you are now storing the config into the correct component. But then in `plagiarism_plugin_unplag::get_settings()` you load if from the legacy location again.

Additionally, this become non-sense now:

```
$plagiarismsettings = array_merge((array)get_config('plagiarism_unplag'), (array)get_config('plagiarism_unplag'));
```

**Comment by Unplag** [comment]
fixed!
